### ISSUE TITLE
Unable to access database in Kafka consumer.

### ISSUE THREAD

**Issue by illenko** [gofr-dev/gofr#583]
Unable to access database in Kafka consumer, the same code works correctly in the handler.

**Sample application:**
* config
```env
APP_NAME=transaction-service
HTTP_PORT=8080

PUBSUB_BACKEND=KAFKA
PUBSUB_BROKER=localhost:29092
CONSUMER_ID=transaction-service

DB_HOST=localhost
DB_USER=postgres
DB_PASSWORD=postgres
DB_NAME=postgres
DB_PORT=5432
DB_DIALECT=postgres
```

* db table
```sql
create table transaction
(
    id    integer,
    title varchar
);
```

* main.go (error handling omitted)
```go
package main

import (
	"gofr.dev/pkg/gofr"
)

type transaction struct {
	Id    int
	Title string
}

func main() {
	app := gofr.New()

	app.Subscribe("transaction-topic", func(c *gofr.Context) error {

		rows, err := c.SQL.QueryContext(c, "SELECT id, title FROM transaction")

		defer rows.Close()

		return nil
	})

	app.GET("/transactions", func(c *gofr.Context) (interface{}, error) {
		var transactions []transaction

		rows, err := c.SQL.QueryContext(c, "SELECT id, title FROM transaction")

		for rows.Next() {
			var t transaction
			err := rows.Scan(&t.Id, &t.Title)
		
			transactions = append(transactions, t)
		}

		defer rows.Close()

		return transactions, nil
	})
	app.Run()
}

```

Error Trace: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xcff647e]

goroutine 42 [running]:
gofr.dev/pkg/gofr.(*Context).Done(0xcf8b18a?)
        <autogenerated>:1 +0x1e
database/sql.(*DB).conn(0xc00047b790, {0xd43faa0, 0xc000538fc0}, 0x1)
        /Users/user/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.darwin-amd64/src/database/sql/sql.go:1318 +0xdd
database/sql.(*DB).query(0xc00047b790, {0xd43faa0, 0xc000538fc0}, {0xd01a1ca, 0x21}, {0x0, 0x0, 0x0}, 0xc0?)
        /Users/user/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.darwin-amd64/src/database/sql/sql.go:1749 +0x57
database/sql.(*DB).QueryContext.func1(0x68?)
        /Users/user/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.darwin-amd64/src/database/sql/sql.go:1732 +0x4f
database/sql.(*DB).retry(0x10?, 0xc000567de8)
        /Users/user/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.darwin-amd64/src/database/sql/sql.go:1566 +0x42
database/sql.(*DB).QueryContext(0x54b89f38?, {0xd43faa0?, 0xc000538fc0?}, {0xd01a1ca?, 0xe07f108?}, {0x0?, 0x11?, 0x0?})
        /Users/user/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.darwin-amd64/src/database/sql/sql.go:1731 +0xc5
main.main.func1(0xc000114090?)
        /Users/user/IdeaProjects/gofr-try/main.go:17 +0x59
gofr.dev/pkg/gofr.(*SubscriptionManager).startSubscriber(0xc00045d080, {0xd007106, 0x11}, 0xd4298c8)
        /Users/user/go/pkg/mod/gofr.dev@v1.4.0/pkg/gofr/subscriber.go:37 +0x1e8
created by gofr.dev/pkg/gofr.(*App).Run in goroutine 1
        /Users/user/go/pkg/mod/gofr.dev@v1.4.0/pkg/gofr/gofr.go:162 +0x559

```

**Comment by aryanmehrotra** [comment]
@illenko I tried debugging this issue on version v1.4.0 and the latest version as well.
But it works fine, can you share more logs on the same.

Also, what is the go version in your go.mod file?

**Comment by illenko** [comment]
@aryanmehrotra , please find this repo with simple replication example: https://github.com/illenko/gofr-issue-replication

**Comment by aryanmehrotra** [comment]
@illenko can you update the go version to 1.21 in the go.mod file?
It seems to be a toolchain issue.

**Comment by illenko** [comment]
@aryanmehrotra if I use `c.SQL.Query` instead of `c.SQL.QueryContext` it works.

**Comment by aryanmehrotra** [comment]
`QueryContext` implementation is missing from `pkg/gofr/datasource/sql/db.go`

**Comment by illenko** [comment]
> ```go
> QueryContext
> ```

It works in the scope of handler func.
