### ISSUE TITLE
App panics during start for AddRESTHandlers

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#858]
**Describe the bug**
When using the functionality `AddRESTHandlers` and passing the struct by value i.e
```
err := app.AddRESTHandlers(Level{})
```

application panics and gives the following logs:

```
INFO [12:12:39] Loaded config from file: ./configs/.env
INFO [12:12:39] connected to 'log-level' database at 'localhost:2001'
panic: reflect: Elem of invalid type main.Level

goroutine 1 [running]:
reflect.elem(0x140005cfc48?)
        /opt/homebrew/opt/go/libexec/src/reflect/type.go:712 +0xc4
reflect.(*rtype).Elem(0x28?)
        /opt/homebrew/opt/go/libexec/src/reflect/type.go:716 +0x20
gofr.dev/pkg/gofr.scanEntity({0x1014fa760, 0x140000c2420})
        /Users/raramuri/go/pkg/mod/gofr.dev@v1.14.1/pkg/gofr/crud_handlers.go:64 +0x58
gofr.dev/pkg/gofr.(*App).AddRESTHandlers(0x14000117440, {0x1014fa760, 0x140000c2420})
        /Users/raramuri/go/pkg/mod/gofr.dev@v1.14.1/pkg/gofr/gofr.go:457 +0x30
main.main()
        /Users/raramuri/Desktop/gofr-app/main.go:39 +0xd4
exit status 2
```

**Expected behavior**
It should not panic rather startup should fail with the error that, failed to register routes for \<struct-name>, as it is passed by value should be pointer

**Comment by srinivas365** [comment]
https://github.com/gofr-dev/gofr/pull/864

**Comment by srinivas365** [comment]
https://github.com/gofr-dev/gofr/pull/864

**Comment by srijan-27** [comment]
@srinivas365 - Since, you are working on this so, assigning this to you
